### ISSUE TITLE
Possibly hash/checksum all .cmd/.bat/.sql/.vbs files and store the hash in another file to ensure they are not modified

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#109]

**Comment by PiJoCoder** [comment]
@troymoen1 , @gambit9009

**Comment by PiJoCoder** [comment]
@liweiyin1113 can you see this?

**Comment by Liwei-Yin** [comment]
yup,I see this, thanks Joseph.

**Comment by PiJoCoder** [comment]
> yup,I see this, thanks Joseph.

Thanks @Liwei-Yin

**Comment by PiJoCoder** [comment]
This has been done - https://github.com/microsoft/DiagManager/pull/123
