### ISSUE TITLE
Profiler trace it includes Service Broker events, for XEvents it does not

### ISSUE THREAD

**Issue by gambit9009** [microsoft/DiagManager#110]
Service Broker issues might be rare, but having an event enabled that doesn't add overhead to the capture would be helpful to have.  Thought would be if we collected it in Trace, probably we should get it in XEvent by default.

For Trace we would get Broker:
Connection
Corrupted Message
Forward Message Dropped
Message Undeliverable

**Comment by PiJoCoder** [comment]
The ask is to get SQL Trace and Xevent at par - make the same defaults - in General and Detailed Scenarios

Xevents: 
broker_corrupted_message
broker_Forward_Message_Dropped
broker_Message_Undeliverable

**Comment by PiJoCoder** [comment]
Already added to SQL LogScout 281
