### ISSUE TITLE
Add a Query-Never-Completes Scenario to Capture Data in PSSDIAG

### ISSUE THREAD

**Issue by gambit9009** [microsoft/DiagManager#114]
Moved from other DiagManager Issues

Using Lightweight profiling infrastructure

Started building code based on https://docs.microsoft.com/en-us/sql/relational-databases/performance/query-profiling-infrastructure?view=sql-server-ver15

**Comment by PiJoCoder** [comment]
This has been completed - see https://github.com/microsoft/DiagManager/pull/130
