### ISSUE TITLE
Duplicating a parameter when calling sqldiag leads to nondescript error

### ISSUE THREAD

**Issue by troymoen1** [microsoft/DiagManager#118]
e.g.

sqldiag /I pssdiag.xml /I "C:\Users\user\OneDrive - Microsoft\CodeDevelopment\Repos\DiagManager\DiagManager\Pristine\pssdiag.xml"

**Comment by gambit9009** [comment]
If this sample given is what was being run, that message would be coming from SQLDiag, which comes with SQL Server.  

When running PSSDiag.ps1, we get a clear message that a duplicate parameter was given more than once...

![image](https://user-images.githubusercontent.com/22751647/163268239-a31f1af4-db91-4e97-8fb4-a1f559a2ae7b.png)
