### ISSUE TITLE
Service Broker Custom Collector doesn't work

### ISSUE THREAD

**Issue by NathanMSFT** [microsoft/DiagManager#126]
I configured PSSDiag to gather Service Broker at Shutdown Custom Diagnostic, but there's no output files that were produced that were Service Broker related. SQLDIAG.LOG showed the following, which indicates to me that it "tried" to run something

{datetime} SERVER\INSTANCE Service Broker: Service Broker

I also checked the extracted sql/cmd/exe/js files and see nothing that is related to Service Broker as a specific script to run when the Service Broker Custom Diagnostic is selected.

**Comment by PiJoCoder** [comment]
@NathanMSFT would you like to work on this one yourself - I'd be happy to provide guidance

**Comment by NathanMSFT** [comment]
@PiJoCoder - sure, I will need help getting VS Code setup for the repo, but this would be a good way to get my feet wet :)

**Comment by PiJoCoder** [comment]
Hey, I'll be glad to help. If you have Visual Studio you are all set up .
Let me know and I can help you clone the repo and set you up to go from there. Yes, that was exactly the intention to get you started.

Thanks

**Comment by PiJoCoder** [comment]
Discussed with Nathan - no repro . Closing
