### ISSUE TITLE
Unable to find SQL Server client tools such as sqldiag.exe 

### ISSUE THREAD

**Issue by ESLCH** [microsoft/DiagManager#13]
Hi,
unable to lunch pssdiag on SQL SErver 2016 SP1 on windows 2016 standard:

C:\Temp\pssd>pssdiag.cmd
2017/10/22 12:45:04.97 SQLDIAG Collector version
2017/10/22 12:45:04.99 SQLDIAG

IMPORTANT:  Please wait until you see "Collection started" before attempting to reproduce your issue
2017/10/22 12:45:05.01 SQLDIAG Output path: C:\Temp\pssd\output\
2017/10/22 12:45:05.03 SQLDIAG Error opening HKLM key . Function result: 53. Message: The network path was not found.
2017/10/22 12:45:05.03 SQLDIAG Error opening HKLM key . Function result: 53. Message: The network path was not found.
2017/10/22 12:45:05.03 SQLDIAG Error opening HKLM key . Function result: 53. Message: The network path was not found.
2017/10/22 12:45:05.03 SQLDIAG Error opening HKLM key . Function result: 53. Message: The network path was not found.
2017/10/22 12:45:05.03 SQLDIAG Error opening HKLM key . Function result: 53. Message: The network path was not found.

2017/10/22 12:45:05.04 SQLDIAG There are no instances of version 13 on this computer

2017/10/22 12:45:05.04 SQLDIAG . Function result: 87. Message: The parameter is incorrect.

**Comment by billhol** [comment]
Pssdiag should be run on the same system that is running SQL Server. OS error 53 indicates there is a network name resolution or a network connectivity problem at the OS level. You can test connecivity by attempting to telnet to SQL Server’s IP address and port. If telnet fails, you should investigate where SQL Server’s port is open and SSCM has allowed SQL Server to use its TCP netlibrary, but you really should be running pssdiag on SQL Server’s system (I.e. not across a network wire).
