### ISSUE TITLE
When will PSSDiag be released for SQL Server 2017 ?

### ISSUE THREAD

**Issue by diegocaracciolo** [microsoft/DiagManager#14]
We are running SQL Server 2017 in production now and we would like to capture data with PSSDiag. Thanks

**Comment by JosephOBrienDBA** [comment]
Again Microsoft. Why are paying customers waiting for this critical tool to diagnose performance issue. I'll bet a zillion dollars the support organization has support for 2017 and 2019.

**Comment by Dwayne75** [comment]
Edit the pssdiag.xml and change the version to 14
<Instance name="*" user="" windowsauth="true" ssver="14">
as a workaround

**Comment by PiJoCoder** [comment]
See the [latest several versions](https://github.com/microsoft/DiagManager/releases/tag/Win16.22.03.16) that support from SQL 2008 - 2019 

Also, remember that SQL Server ships with [SQLDiag.exe](https://docs.microsoft.com/en-us/sql/tools/sqldiag-utility?view=sql-server-ver15), which is what this tool uses under the covers. You can run it locally on your system to capture Perfmon and Xevents to get the analysis going.
