### ISSUE TITLE
Possible way to call SQLDiag without opening 2nd window but still acts as expected.

### ISSUE THREAD

**Issue by gambit9009** [microsoft/DiagManager#146]
In the past we had tried different things and had different issues with the PS1 starting SQLDiag.exe with the parameters.  I don't remember the exact issues but in short...
1.  Opening in 2nd window, if SQLDiag gets an error, the process is considered exited and the window closes.  Users wont see the error on the screen. We used StartProcess to open SQLDiag in a new window ...but then had the PS1 print the last 5 lines of the console log recorded by SQLDiag with that window closed just to show if there were any errors.  
2. We used StartProcess to run SQLDiag in the same window in PS.  Had weird results where, when SQLDiag finished, the live cursor was up in the text that SQLDiag had output to the console.  We wanted one window but it just didnt act right.

We may have found a way around the 2nd window using Call operator (&):
  Syntax:           &   "[path] command"    [arguments]

Sample lines....
$arguments = "/I", "pssdiag.xml", "/O", "output", "/P", "/N", "1", "/C", "0"
$sdexec = "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\sqldiag.exe"
& $sdexe $arguments

("$arguments" is an array with all the command line params we want.  Using =+ we can keep adding parameters to the array.)

**Comment by PiJoCoder** [comment]
Tested with multiple parameter -B -E -R -U -P START STOP looks good
