### ISSUE TITLE
Row duplicated for "requests" on SQL 2008 R2 data collection PerfStats

### ISSUE THREAD

**Issue by FonsecaSergio** [microsoft/DiagManager#15]
Not sure how that happen on PerfStats data collection and how to reproduce the same problem, but it caused a cause confusion when looking into blocking information when joining stuff with "requests" data

Look on session 3170 and ecid all = 0

[requests.txt](https://github.com/Microsoft/DiagManager/files/1511071/requests.txt)

**Comment by gambit9009** [comment]
Issue #68 and #15 are tied together.  Closing this one.
