### ISSUE TITLE
Update TempdbUsage script that captures information about tempdb space usage

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#150]
**Do you want to request a *feature* or report a *bug*?**
Enhacement

**What is the current behavior?**

**What is the expected behavior?**
Collect more relevant information by adding a few more DMVs and clean up the existing

**Comment by gambit9009** [comment]
@setanike-msft  Based on conversation, @PiJoCoder mentioned you were working on

**Comment by gambit9009** [comment]
'-- sys.dm_db_session_space_usage --' is at least one place where zeros are returned

**Comment by PiJoCoder** [comment]
- Get only rows where allocated pages in tempdb is greater than 0 or some number
- Remove usage of sys.processes and replace with other DMVs
- Add a PRINT '' statement after each query so we have an empty line between rowsets - needed by SQLNexus
- Remove SELECT * where possible
- SET ROWCOUNT ON - remove rowcounts

**Comment by gambit9009** [comment]
We did a lot of clean up but still have a lot to do.

**Comment by PiJoCoder** [comment]
Related Commits:

4be2b759953cb39d028900e87ac6b10ac806da2f
a32593e4351d0b3dbfa7ed589947de24e12e6c0c
8c0b255e5327bf4456bad6fea358aca9b82115ca
