### ISSUE TITLE
Error 468 Cannot resolve the collation conflict when running XE query inside MiscPssdiagInfo.sql 

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#157]
**Do you want to request a *feature* or report a *bug*?**
Bug. 

**What is the current behavior?**

When databases are with different collation from that of Master, you may get Msg 468 when this query runs:

print '--XEvent Session Details--'
SELECT convert(nvarchar(128), sess.NAME) as 'session_name', convert(nvarchar(128), event_name) as event_name,
CASE
WHEN xemap.trace_event_id IN ( 23, 24, 40, 41,44, 45, 51, 52,54, 68, 96, 97,98, 113, 114, 122,146, 180 )
THEN Cast(1 AS BIT) ELSE Cast(0 AS BIT)
END AS expensive_event
FROM sys.dm_xe_sessions sess
INNER JOIN sys.dm_xe_session_events evt 
ON sess.address = evt.event_session_address
INNER JOIN sys.trace_xe_event_map xemap
ON evt.event_name = xemap.xe_event_name

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem **

**What is the expected behavior?**

No error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

All supported versions

**Comment by PiJoCoder** [comment]
https://github.com/microsoft/DiagManager/pull/153/commits/fad1f92a25f0eaff054bb463412e5d32cb4dfe25

**Comment by PiJoCoder** [comment]
already being fixed

**Comment by mdaniou** [comment]
it seems like this commit hasn't been merged

**Comment by PiJoCoder** [comment]
> it seems like this commit hasn't been merged

https://github.com/microsoft/DiagManager/pull/153/files
