### ISSUE TITLE
Convert the Errorlog collector scripts in SQL Base to a PowerShell script

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#167]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Using T-SQL and a Javascript file

**What is the expected behavior?**
Create a PS1 file to do the work of collecting logs. You can borrow the logic from here - https://github.com/microsoft/SQL_LogScout/blob/main/SQL%20LogScout/SQLLogScoutPs.ps1#:~:text=function%20GetSQLErrorLogsDumpsSysHealth()

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All supported versions

**Comment by Peter-Msft** [comment]
PR created: https://github.com/microsoft/DiagManager/pull/176
