### ISSUE TITLE
Consider only getting ERRORLOG files below a certain size and for the remaining large files get first and last 500 lines or so

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#174]
**Do you want to request a *feature* or report a *bug*?**
Feature  - reduce the collection of unnecessary ERRORLOG info by PSSDIAG. 
We can set them at 1 GB 

**What is the current behavior?**
We currently get entire files even if they are 2 MB or 100 GB is size

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem **

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
All versions

Currenly geting errorlogs is re-written into a PowerShell script. We could consider adding logic in the future to only copy files of certain size. 

Adding some pseudocode

```PowerShell
 Get-ChildItem  -File | Where-Object {($_.Length -lt 1073741824) -and ($_.Length -gt 0)} | Copy-Item....
```

And for files that are larger files (prototype)

```Powershell

$errorlog_path  = "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Log"
$outpu_path = "C:\temp\OutputFolder"

$errorlog_gt_1gb =  (Get-ChildItem  -Path $errorlog_path  -File -Filter "ERRORLOG*" | Where-Object {($_.Length -ge 1073741824) -and ($_.Length -gt 0)} | Select-Object Name).Name


$errorlog_gt_1gb 

foreach ($filename in $errorlog_gt_1gb)
{
  Write-Host ($outpu_path + "\" + $filename+"_Head_and_Tail_Only")
  Get-Content $filename -TotalCount 300  | Set-Content -Path ($outpu_path + "\" + $filename+"_Head_and_Tail_Only") 
  Write-Host "*************************************************"
  Add-Content -Value "`n   <<... middle part of file not captured because the file is too large (>1 GB) ... >>`n" -Path ($outpu_path + "\" + $filename+"_Head_and_Tail_Only") 
  Get-Content $filename -Tail 300 | Add-Content -Path ($outpu_path + "\" + $filename+"_Head_and_Tail_Only")
}

```

**Comment by Peter-Msft** [comment]
PR created: https://github.com/microsoft/DiagManager/pull/206
