### ISSUE TITLE
PSSdiag won't trace SQL Server 2016 SP2 instances

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [microsoft/DiagManager#20]
Because of a discrepancy in SP2 version number in registry, SQLDIAG/PSSDiag won’t be able to discover and trace a SQL Server 2016 SP2 instance.

Using “.” For machine and “*” for instance will NOT detect the SP2 instance. Even using the instance name explicitly will not work.

The manual workaround is to force instance name AND use wildcard * (instead of 13) in SQL version in PSSDiag XML :
Eg for a default instance : <Instance name="MSSQLSERVER" user="" windowsauth="true" ssver="*">

And if you do that with pssdiag you will get a msgbox prompt as follows :

> ---------------------------
> Unable to find SQL Server client tools such as sqldiag.exe from this machine.  Data collection will fail
> ---------------------------
> OK   
> ---------------------------

Ignore and proceed, it should work.

**Comment by nysot** [comment]
you need to change the instance name to "MSSSQLSERVER" also
see [https://blogs.msdn.microsoft.com/sqlserverfaq/2011/04/05/sqldiag-there-are-no-instances-of-version-10-on-this-computer/](url) here

**Comment by Guillaume-Fourrat** [comment]
> 
> 
> you need to change the instance name to "MSSSQLSERVER" also
> see [https://blogs.msdn.microsoft.com/sqlserverfaq/2011/04/05/sqldiag-there-are-no-instances-of-version-10-on-this-computer/](url) here

Well, yes, this is what I meant by stating "The manual workaround is to force instance name". So MSSQLSERVER indeed for default instance, but there's also the situation of named instances.
The article you mention is a general guidance for PSSDiag, while the issue discussed here is specific to SQL 2016 SP2.

**Comment by nysot** [comment]
While the article is generic, I also encountered issues on SQL 2016 SP2 and that’s what saved the day . . . .

[cid:image001.png@01D53CB0.1C3AE4B0]

`Tosin Shobukola  |  Premier Field Engineer – Data Platform  | MEA
È + 234-813-911-8999 |  •  tosin.shobukola@microsoft.com<mailto:tosin.shobukola@microsoft.com> |

Big Data & Advanced Analytics<https://azure.microsoft.com/en-us/solutions/big-data/>  | SQL Server<https://www.microsoft.com/en-us/server-cloud/products/sql-server> | Artificial Intelligence<https://www.microsoft.com/en-us/ai/default.aspx> | PowerBI<https://powerbi.microsoft.com/en-us/features/> | IOT<https://www.microsoft.com/en-sa/internet-of-things/>
