### ISSUE TITLE
WaitForExe.cmd placed in quarantine

### ISSUE THREAD

**Issue by jdschuitemaker** [microsoft/DiagManager#218]
I downloaded the zip-file and extracted it to a folder and then got a message from our Cisco AMP antivirus software:

`WaitForExe.cmd has been detected as W32.Auto:8943003b4e.in05Talos. Quarantine was successful`

**Comment by PiJoCoder** [comment]
@jdschuitemaker can you please clarify which .zip file was downloaded? The PSSDIAG releases for the past couple of years contain no .EXEs or .DLLs.  Please see https://github.com/microsoft/DiagManager/releases

**Comment by PiJoCoder** [comment]
@jdschuitemaker, just wanted to inform you that we run the tool through anti-virus validation before we release it. 
Just now again validated PSSDIAG_v_16_22_11_11.zip with VirustTotal.com, which validates the file against 50 or 60 different malware providers and "No security vendors and no sandboxes flagged this file as malicious"
Thank you

**Comment by jdschuitemaker** [comment]
Thank you very much for the update!

**Comment by PiJoCoder** [comment]
@jdschuitemaker I have one more update for you. You can safely delete this file from your pssdiag folder. It is left over from previous functionality and it's not used by any component. 
I made that change to it and some other files in the code and a future release will have this file removed.

See #219

**Comment by jdschuitemaker** [comment]
Thank you, I will keep an eye on the new release.
