### ISSUE TITLE
Feature Request: Open existing PSSDIAG packages to veiw/edit config

### ISSUE THREAD

**Issue by coffeecanary** [microsoft/DiagManager#24]
One use case I would like to see enabled is opening an existing PSSDIAG package to view the current settings and to be able to make changes if necessary and save that package or save as a new package.

It would be nice to be able to see what data will be collected in a PSSDIAG I am being asked to run. 

Alternatively, if I build a package and send to a customer, if we need to make changes, it would be nice to open the existing one, and make small changes to the data collection set, and save it. This would make it easier to make iterative changes over time until the data collection set is finalized.

**Comment by PiJoCoder** [comment]
Thank you for the idea. This is a major feature request and it would require a lot of engineering effort. Not possible at this point.
