### ISSUE TITLE
pssdiag output

### ISSUE THREAD

**Issue by sakurai8888** [microsoft/DiagManager#25]
May I know if the pssdiag output of customized sql can output to xls??

and anyway I can output execution plan from pssdiag to xml format ?

**Comment by billhol** [comment]
You can use https://github.com/Microsoft/SqlNexus to import pssdiag output, and export its ReadTrace reports to XLS.

Be careful when using DiagManager to capture Showplan XML events. The Showplan XML event is a very large event, which on a busy system can noticeably impact SQL Server's performance. SqlNexus imports the old Showplan Statistics Profile event from pssdiag's trace files, not Showplan XML (even when DiagManager has been configured to collect both). While Showplan Statistics Profile is not as rich as Showplan XML, SQLNexus will lead you to the most common execution performance problems, such as index of table scans, poor cardinality estimates, and the large consumers of reads, writes, or CPU time. You can export the Showplan XML event from pssdiag's trace files or extended event output, but you will have to research on the internet about how to export that event programatically or manually. The database SQLNexus creates (by importing and aggregating pssdiag's output) is likely to be sufficient for your needs (even though it will not be Showplan XML). The database small when compared to pssdiag's output, and cab be backed up/archived. With experience the database's tables and views can be queried to reveal more far details than what SQL Nexus' reports reveal.

**Comment by PiJoCoder** [comment]
You can write a [custom collector ](https://github.com/microsoft/DiagManager/wiki/Creating-Custom-Collectors) that runs scripts and exports to a CSV (comma-delimited) file. 
Probably the best option is for your custom collector to run BCP query and output to a comma as a field terminator ([-t field terminator])
