### ISSUE TITLE
how to get the pssidag installer for SQL Server 2017 ? 

### ISSUE THREAD

**Issue by SamarendraPanda** [microsoft/DiagManager#27]
Is there anyway we can have the public download for the pssdiag #14.0.1600.41 which can take the data from SQL Server 2017 ?

**Comment by mRWSEI** [comment]
I was able to run it changing ssver section in xmlconfig file, but SQLDiag still doesnt write profiler *.trc files to disk which are the most important for me...

**Comment by PiJoCoder** [comment]
I know this response is way late, but we are sweeping to Issues and I saw this. Hope this image answers both of these questions. Latest windows release can be found here https://github.com/microsoft/DiagManager/releases/tag/Win16.22.03.16 

![image](https://user-images.githubusercontent.com/23519517/163482644-26dbd1cc-6bca-4687-8098-2853c7f0c259.png)
