### ISSUE TITLE
The Trace Event "Exec Prepared SQL" is Missing for "Replay" Scenario

### ISSUE THREAD

**Issue by ShiyangQiu** [microsoft/DiagManager#3]
The trace event "Exec Prepared SQL" is missing for "Replay" scenario.
![sqldiag](https://cloud.githubusercontent.com/assets/16111972/24141790/8c5750c0-0e5f-11e7-91ab-ec195e635842.jpg)

**Comment by ShiyangQiu** [comment]
I tested to modify file \Templates\SQLTraceEvent_Template.xml to find id 72 then add a Scenario 

&lt;EventType name=&quot;TSQL&quot;&gt; &lt;Event name=&quot;Exec Prepared SQL&quot; id=&quot;72&quot;&gt; &lt;Scenarios&gt; &lt;Scenario name=&quot;Replay&quot; enabled=&quot;true&quot;/&gt; &lt;/Scenarios&gt;

and it's fixed..

**Comment by PiJoCoder** [comment]
Fixed based on your [PR](https://github.com/microsoft/DiagManager/pull/4). Thank you!
