### ISSUE TITLE
PSSDIAG data loading to SQL NEXUS 

### ISSUE THREAD

**Issue by KollSud** [microsoft/DiagManager#34]
PSSDIAG data loading through SQL NEXUS is taking too much time..

Process : Post-load data clean up
Procedure : "ReadTrace.usp_perfromPostLoadFixups"
Statement : Update ReadTrace.TableStatements

Is there any workaround for quick data loading?

**Comment by PiJoCoder** [comment]
Thank you @KollSud. This is more of a [RML Utilities](https://docs.microsoft.com/en-us/troubleshoot/sql/tools/replay-markup-language-utility) question than PSSDIAG. ReadTrace, which is part of RML is invoked by SQLNexus to import XEvent or Profiler data. Based on the query that you are providing above I am guessing that the data set used in your import was probably large and was using detailed tracing (statement level events). This could be millions of rows of data. Not sure about the specifics of this update, but as you can see this is simply an UPDATE statement and on the SQL Server side. 
As far as workarounds - one way to approach it is not to collect statement-level events, if you do not need them.  But if you do need them, you may have to exercise patience. If you want to import the data in alternative ways (like using [sys-fn-xe-file-target-read-file](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-xe-file-target-read-file-transact-sql) ) you may find it takes even longer. ReadTrace.exe is typically the fastest approach.
Hope this helps.
