### ISSUE TITLE
Collect ADR related DMV output

### ISSUE THREAD

**Issue by jaynar-cts1** [microsoft/DiagManager#44]
Collect ADR DMV output

select * From  sys.dm_tran_persistent_version_store_stats 
select * From  sys.dm_tran_aborted_transactions

**Comment by PiJoCoder** [comment]
Partly accomplished already in 66421bb95d0cd8d0293b58b48374cd9d8751be50

**Comment by gambit9009** [comment]
also add those in textrowsets..xml in SQL nexus.  Added issue there:  https://github.com/microsoft/SqlNexus/issues/168
