### ISSUE TITLE
the Pssdiag blocks other processes in SQL Server

### ISSUE THREAD

**Issue by declare2006** [microsoft/DiagManager#45]
Hi admin,  I use DiagManager13.0.1600.32 to generate the pssdiag file. please see the attachment for configuration(this configuration file is xml file but I cannot upload xml file here , so I change the suffix of this file to be txt). 
The target SQL server is SQL 2014. When I begin to run Pssdiag.cmd, the CPU usage begin to drop(from 60% drop to 20%);after I stop Pssdiag, the CPU usage begin to up (from 20% to 70). And during the running of Pssdiag, the data loading of SQL Server is blocked until Pssidiag is stopped.

previously I only know Pssdiag can result in high CPU usage; it is the first time that I see Pssdiag can make CPU usage down. And I have not encounter the blocking issue result from Pssdiag before. 

[pssdiag.txt](https://github.com/microsoft/DiagManager/files/3836490/pssdiag.txt)

**Comment by PiJoCoder** [comment]
Apologize for delay in response. It would be hard to diagnose the issue based on the configuration XML file. This has not been reported before and we have not observed it. We would have to see the specific queries that may be causing the blocking to t-shoot further. Please reopen if you encounter.
