### ISSUE TITLE
Transactions counter prefixed with double colons

### ISSUE THREAD

**Issue by Dimka12** [microsoft/DiagManager#5]
In SQLPerfmon_Template.xml on the line **<PerfmonObject name="\MSSQL$%s::Transactions"**> Transactions prefixed with two colons. Because of that  counter sorted incorrectly in GUI and pssdiag.xml also contains incorrect counter name, that cannot be added to BLG collection.
**Could not add counter: \\<servername>\MSSQL$sql2016::Transactions**

**Comment by PiJoCoder** [comment]
Issue seems to be fixed already - see https://raw.githubusercontent.com/microsoft/DiagManager/master/DiagManager/Templates/SQLPerfmon_Template.xml
