### ISSUE TITLE
enabled=false does not disable XEvent collection

### ISSUE THREAD

**Issue by ccurtmath1** [microsoft/DiagManager#54]
If you originally configure pssdiag to collect XEvent session and decide later to disable, you locate the XEvent custom group in the pssdiag.xml file and note the enabled="true" and modify it to enabled="false"

However running pssdiag you will observe that the XEvent session is still captured.

Setting enabled to false should eliminate XEvent data collection.

**Comment by suresh-kandoth** [comment]
If you do not need XEvent custom collector to gather any data at all, you should remove this CustomGroup section from the PSSDIAG.XML data. PSSDIAG invokes the custom group if the entry for that custom group or task is present.

                <CustomGroup name="XEvent " enabled="true">
                  <CustomTask enabled="true" groupname="XEvent " taskname="Creating Event Session" type="TSQL_Script" point="Startup" wait="Yes" cmd="pssdiag_xevent.sql" pollinginterval="0" />
                  <CustomTask enabled="true" groupname="XEvent " taskname="Add File Target" type="TSQL_Command" point="Startup" wait="Yes" cmd="alter EVENT SESSION [pssdiag_xevent] ON SERVER   ADD TARGET package0.event_file(SET filename=N'%output_path%%server%_%instance%_pssdiag_xevent.xel', max_file_size=(500), max_rollover_files=(50));" pollinginterval="0" />
                  <CustomTask enabled="true" groupname="XEvent " taskname="Starting Event Session" type="TSQL_Command" point="Startup" wait="No" cmd="ALTER EVENT SESSION [pssdiag_xevent]  ON SERVER STATE = start;" pollinginterval="0" />
                  <CustomTask enabled="true" groupname="XEvent " taskname="Stopping Event Session" type="TSQL_Command" point="Shutdown" wait="No" cmd="ALTER EVENT SESSION [pssdiag_xevent]  ON SERVER STATE = stop;DROP EVENT SESSION [pssdiag_xevent] ON SERVER;" pollinginterval="0" />
                </CustomGroup>

**Comment by suresh-kandoth** [comment]
I noticed that if we set the CustomTask to false, then it does not invoke the task. Example:

                <CustomGroup name="XEvent " enabled="true">
                  <CustomTask enabled="false" groupname="XEvent " taskname="Creating Event Session" type="TSQL_Script" point="Startup" wait="Yes" cmd="pssdiag_xevent.sql" pollinginterval="0" />
                  <CustomTask enabled="false" groupname="XEvent " taskname="Add File Target" type="TSQL_Command" point="Startup" wait="Yes" cmd="alter EVENT SESSION [pssdiag_xevent] ON SERVER   ADD TARGET package0.event_file(SET filename=N'%output_path%%server%_%instance%_pssdiag_xevent.xel', max_file_size=(500), max_rollover_files=(50));" pollinginterval="0" />
                  <CustomTask enabled="false" groupname="XEvent " taskname="Starting Event Session" type="TSQL_Command" point="Startup" wait="No" cmd="ALTER EVENT SESSION [pssdiag_xevent]  ON SERVER STATE = start;" pollinginterval="0" />
                  <CustomTask enabled="false" groupname="XEvent " taskname="Stopping Event Session" type="TSQL_Command" point="Shutdown" wait="No" cmd="ALTER EVENT SESSION [pssdiag_xevent]  ON SERVER STATE = stop;DROP EVENT SESSION [pssdiag_xevent] ON SERVER;" pollinginterval="0" />
                </CustomGroup>

I just validated it and that works.

**Comment by suresh-kandoth** [comment]
This behavior is controlled by SQLDIAG.EXE

**Comment by ccurtmath1** [comment]
Ok, that is a nice workaround to preserve your code but want to disable the XEvent trace.

I will share this as a workaround in our talk Thursday.

**Comment by PiJoCoder** [comment]
This applies to all Custom collectors.

**Comment by PiJoCoder** [comment]
Closing. Not an issue with this product.
