### ISSUE TITLE
MSINFO hangs pssdiag collection when run as service

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/DiagManager#65]
Report from Clinton Wong:

Had an interesting issue when running PSSDIAG on my customer’s machine for long-term capture.   Found that it hadn’t been collecting properly as it hung on startup and the cause was MSINFO caused it to hang.

Pretty sure that option is ON by default and it wasn’t me screwing it up, but this might catch others when running PSSDIAG as a service.   Wanted to just let you know in case you start seeing others report it. (Don’t recall this happening in the past :()

**Comment by PiJoCoder** [comment]
This likely because of the pop-up that comes up and it was potentially expecting user to interact with it. We recently switched to using Systeminfo.exe instead  see PR https://github.com/microsoft/DiagManager/pull/136 and this must resolve the issue. Please re-open if not.
