### ISSUE TITLE
Error on SQL 2016 SP1

### ISSUE THREAD

**Issue by qd7259** [microsoft/DiagManager#7]
when running this version(<DiagManagerVersion>13.0.1600.32 Build Date:  06/01/2017</DiagManagerVersio>) got following error on SQL 2016 Sp1:
 SQLDIAG There are no instances of version 13 on this computer

**Comment by PiJoCoder** [comment]
The latest version of PSSDIAG helps with this. When you run the pssdiag.ps1 file, the code catches if the registry key is incorrect and it will tell you.  If you really do not have a SQL 2016 instance and you configured PSSDIAG for 2016, you will also get this error. 
Latest Release: https://github.com/microsoft/DiagManager/releases/tag/Win16.22.03.16
