### ISSUE TITLE
Ensure that when selected SQL2008 defaults to General performance collector 

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/DiagManager#73]

**Comment by gambit9009** [comment]
Currently picked SQL 2008 DOES default to Detailed Perf.  Weird.  
![image](https://user-images.githubusercontent.com/22751647/164341373-ef7885d7-1255-4e3c-892d-0dd0e137883e.png)

SQL 2008 R2 is correct.  Also all other versions are correct.  This should be an easy fix to the default...harder part will be to find the right line and the appropriate XML file :) .

**Comment by gambit9009** [comment]
Found it.  General_Template.xml,  line 240
```
    <DefaultChoice Feature="SQL" Version="10" Profiler="true" Perfmon="true" XEvent="false" EvengLog="true" Sqldiag="true">
      <Scenario name="DetailedPerf"/>
    </DefaultChoice>
```
