### ISSUE TITLE
Unchecking "Collect Event Logs" and "SQLDiag DMVs" Does Not Edit XML

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/DiagManager#74]
from James:

While assisting Kelly on a case, it was requested by the customer to not collect the Event Logs with the pssdiag. We went into pssdiag, selected the “Misc” tab and unchecked the “Shutdown” box under “Collect Event Logs” and found that the pssdiag improperly still collected the .CSVs. After reviewing the XML file it appears that the line properly edited. Manually editing the XML achieves the desired result. As far as testing, we had someone else give it a shot for a different version of SQL and the behavior was consistent.

Is this something that could be amended?

**Comment by gambit9009** [comment]
I remember emails on this.  I can't remember it if might have already been addressed.  Need to test.  I am confused about these 12 statements..." After reviewing the XML file it appears that the line properly edited. Manually editing the XML achieves the desired result. "  Maybe it was that the XML was NOT properly edited at first.  Then manually editing it did fix it.  Or maybe it is "What was manually edited?".   Could it be like issue #54 where the group being true or false didn't matter, the individual entries under the group had to be true or false and SQLDiag didn't look at the whole group?  Need to check

**Comment by PiJoCoder** [comment]
> I remember emails on this. I can't remember it if might have already been addressed. Need to test. I am confused about these 12 statements..." After reviewing the XML file it appears that the line properly edited. Manually editing the XML achieves the desired result. " Maybe it was that the XML was NOT properly edited at first. Then manually editing it did fix it. Or maybe it is "What was manually edited?". Could it be like issue #54 where the group being true or false didn't matter, the individual entries under the group had to be true or false and SQLDiag didn't look at the whole group? Need to check

Investigated this issue. Yes, it is a byproduct of the same issue as #54 . The top , group-level setting does not really impact the enabled/disabled. It has to be done individually. Therefore, I will change it for this particular case, but the large issue for all groups has be considered separately.
