### ISSUE TITLE
large joins in perfstats end up consuming huge memory grants

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/DiagManager#85]
Our own queries end up being big consumers of memory grants causing issues for other queries. We need to start breaking up the large joins to be able to run on large systems. Or start using memory grant hints to control the grants.

we can consider adding MAX_GRANT_PERCENT to the query https://support.microsoft.com/en-us/help/3107401/new-query-memory-grant-options-are-available-min-grant-percent-and-max

One PSSDIAG report had 183 GB memory grant - large 1TB system (SQL 2019)

**Comment by PiJoCoder** [comment]
we can consider adding MAX_GRANT_PERCENT to the query https://support.microsoft.com/en-us/help/3107401/new-query-memory-grant-options-are-available-min-grant-percent-and-max
