### ISSUE TITLE
remove references to 32-bit from the output messages of pssdiag collector

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/DiagManager#96]
When running pssdiag you encounter multiple messages like the following with 32-bit in them. It is misleading.

2017/11/27 17:06:11.43 MACHINE0LENOVO\SQL2016 SQL Server version: 13
2017/11/27 17:06:11.43 MACHINE0LENOVO\SQL2016 Machine name: MACHINE0LENOVO (this machine)
2017/11/27 17:06:11.43 MACHINE0LENOVO\SQL2016 Target machine is not a cluster
2017/11/27 17:06:11.43 MACHINE0LENOVO\SQL2016 Instance: SQL2016 (32-bit)
2017/11/27 17:06:43.54 MACHINE0LENOVO\SQL2016 WARNING: User SureshUser cannot log in to MACHINE0LENOVO\SQL2016 (32-bit). Diagnostics for MACHINE0LENOVO\SQL2016 (32-bit) will not be collected. To address this, ensure you can connect to MACHINE0LENOVO\SQL2016 (32-bit) and restart the collection process
2017/11/27 17:06:43.54 MACHINE0LENOVO\SQL2016 No valid instances from which to collect data
2017/11/27 17:06:44.45 SQLDIAG Initialization starting...

**Comment by PiJoCoder** [comment]
This is a SQLDiag.exe message, can't do much about it here.
