### ISSUE TITLE
Collect sys.dm_server_services as part of standard kit (contains IFI info)

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [microsoft/DiagManager#97]
I've not seen info related to IFI (Instant File Initialization) in PSSDiag.
If that's indeed the case, we should collect dm_server_services which has a convenient instant_file_initialization_enabled column, and provide some other useful info as well (although stuff we should have in other places, whereas IFI is unique).
Since this is SQL 2012+, we can make this a standard collection.

**Comment by PiJoCoder** [comment]
Likely place for this DMV to be collected is MiscPssdiagInfo.sql script

**Comment by PiJoCoder** [comment]
Associated with commits:
[c89e4da](https://github.com/microsoft/DiagManager/pull/185/commits/c89e4da58902a3b66cc1fa190757598cb0c074e0)
[d441241](https://github.com/microsoft/DiagManager/pull/185/commits/d44124175125be7792db571644743ad27f7a66f1)
