### ISSUE TITLE
Availability Group Improvements

### ISSUE THREAD

**Issue by SeanGallardy** [microsoft/DiagManager#98]
Collection data needs updated for Availability Group specific collections. Many items are version specific and do not capture or data capture is incomplete on 2016+ instances.

**Comment by SeanGallardy** [comment]
The last PR had 80% of the updates for this. Still missing distributed ag information.

**Comment by asavioli** [comment]
Good afternoon @SeanGallardy . 

On the last PR we have added some more improvements on the SQL Server Perf Stats Snapshot script, related to Availability Group data collections, handling different columns on different versions. I believe some of the issues (or hopefully all) you noticed were fixed.

**Comment by PiJoCoder** [comment]
@seangallardy were you thinking of adding the Distributed availability group stuff here as part of this Issue. Let us know of a time frame you are thinking about so we can label it correctly (wave 1, wave 2, wave 3, etc.) We are working on prioritizing items.
